### ISSUE TITLE
Wapiti error during scan

### ISSUE THREAD

**Issue by tanujjane** [flipkart-incubator/watchdog#13]
Traceback (most recent call last):
  File "/usr/bin/wapiti", line 11, in <module>
    load_entry_point('wapiti3==3.0.1', 'console_scripts', 'wapiti')()
  File "/usr/lib/python3/dist-packages/wapitiCore/main/wapiti.py", line 1002, in wapiti_main
    wap.attack()
  File "/usr/lib/python3/dist-packages/wapitiCore/main/wapiti.py", line 445, in attack
    self.report_gen.generate_report(self.output_file)
  File "/usr/lib/python3/dist-packages/wapitiCore/report/htmlreportgenerator.py", line 57, in generate_report
    copytree(os.path.join(self.BASE_DIR, self.REPORT_DIR, subdir), os.path.join(output_path, subdir))
  File "/usr/lib/python3.6/shutil.py", line 315, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/wapitiCore/report_template/js'

**Comment by NHPT** [comment]
Try adding a / symbol at the end of the URL

**Comment by NHPT** [comment]
I know that you remove that js folder

**Comment by lyhistory** [comment]
simply quote on the parameters' value solved the issue

**Comment by RM6SS62** [comment]
I'm having the same issue

> wapiti -u https://mydomain.com/

> [*] Launching module permanentxss
Traceback (most recent call last):
  File "/usr/bin/wapiti", line 11, in <module>
    load_entry_point('wapiti3==3.0.1', 'console_scripts', 'wapiti')()
  File "/usr/lib/python3/dist-packages/wapitiCore/main/wapiti.py", line 1002, in wapiti_main
    wap.attack()
  File "/usr/lib/python3/dist-packages/wapitiCore/main/wapiti.py", line 445, in attack
    self.report_gen.generate_report(self.output_file)
  File "/usr/lib/python3/dist-packages/wapitiCore/report/htmlreportgenerator.py", line 57, in generate_report
    copytree(os.path.join(self.BASE_DIR, self.REPORT_DIR, subdir), os.path.join(output_path, subdir))
  File "/usr/lib/python3.7/shutil.py", line 315, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/wapitiCore/report_template/js'

Quoting the URL makes no difference.

**Comment by renaudnotes** [comment]
It's probably not the clean and definite answer, but simply create the directory (and you can leave it empty) : 
`mkdir /usr/lib/python3/dist-packages/wapitiCore/report_template/js`

**Comment by ramiroluz** [comment]
Looks like a broken package, someone said in a thread on SourceForge. Copying the files from the git repo also works.

**Comment by HillGnur** [comment]
> simply quote on the parameters' value solved the issue

It solved me at first try, tks mate!
