### ISSUE TITLE
ImportError: No module named wappalyzer

### ISSUE THREAD

**Issue by AnoAlex** [flipkart-incubator/watchdog#14]
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from start_scans import start_scan
  File "/home/---/watchdog/start_scans.py", line 7, in <module>
    from findTechnology import technologyScan
  File "/home/---/watchdog/findTechnology.py", line 1, in <module>
    from wappalyzer import Wappalyzer
ImportError: No module named wappalyzer

**Comment by kotireddyaluri** [comment]
Struggling with the Same problem

**Comment by CRO-THEHACKER** [comment]
Super easy fix, all you have to is install the wappalyzer pip, simply just run
`sudo -H pip install -r external-requirements.txt`
to install the required pip's. - This will install in super-user but allow modify things in $HOME/enable caching.
Hope this helps!
_*hint: Make sure your in the /watchdog/ dir - were you installed the repo._

**Comment by VigneshSahoo** [comment]
![image](https://user-images.githubusercontent.com/54697837/147464087-38a7effc-2528-4b76-954c-0cbf8c8b7f81.png)

Not working!! Have the same problem. @CRO-THEHACKER

**Comment by CRO-THEHACKER** [comment]
> ![image](https://user-images.githubusercontent.com/54697837/147464087-38a7effc-2528-4b76-954c-0cbf8c8b7f81.png)
> 
> Not working!! Have the same problem. @CRO-THEHACKER 

Try running in Python 3.8+

**Comment by VigneshSahoo** [comment]
@CRO-THEHACKER , No use because the code is in Python 2. Look at the space after python print

![image](https://user-images.githubusercontent.com/54697837/147492662-3a4eae2f-ebc0-42b3-bb9d-c05d984d8107.png)

**Comment by abhishekpalad** [comment]
Open findTechnology.py and make the w capital "Wappalyzer"

![image](https://user-images.githubusercontent.com/90696309/180934769-80a92162-96d6-447b-a6d3-76df2e1ace3f.png)
