### ISSUE TITLE
error wapiti when run scan

### ISSUE THREAD

**Issue by fferraro87** [flipkart-incubator/watchdog#6]
hi every time i run a new scan i've that error : 
```
Traceback (most recent call last):
  File "/usr/local/bin/wapiti", line 4, in <module>
    __import__('pkg_resources').run_script('wapiti==2.3.0', 'wapiti')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/wapiti-2.3.0-py2.7.egg/EGG-INFO/scripts/wapiti", line 471, in <module>
    wap.attack()
  File "/usr/local/lib/python2.7/dist-packages/wapiti-2.3.0-py2.7.egg/EGG-INFO/scripts/wapiti", line 207, in attack
    self.__initAttacks()
  File "/usr/local/lib/python2.7/dist-packages/wapiti-2.3.0-py2.7.egg/EGG-INFO/scripts/wapiti", line 128, in __initAttacks
    mod_instance = getattr(mod, mod_name)(self.http_engine, self.reportGen)
  File "/usr/local/lib/python2.7/dist-packages/wapiti-2.3.0-py2.7.egg/wapitiCore/attack/mod_nikto.py", line 78, in __init__
    resp = self.HTTP.send(nikto_req)
  File "/usr/local/lib/python2.7/dist-packages/wapiti-2.3.0-py2.7.egg/wapitiCore/net/HTTP.py", line 508, in send
    verify=self.verify_ssl)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='cirt.net', port=80): Max retries exceeded with url: /nikto/UPDATES/2.1.5/db_tests (Caused by ReadTimeoutError("HTTPConnectionPool(host='cirt.net', port=80): Read timed out. (read timeout=1)",))
```

how can i fix?

Thanks

**Comment by mohangcsm** [comment]
This is an issue with Wapiti service itself. We are replacing the same in the coming version of watchdog.
